# Generated by Django 5.2 on 2025-05-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_producto_imagen_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
    ]
