"""
Django settings for proyecto_final project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=#=bc(q(z)9sdo=ileas3v8(3pbw=6)4qzfu*t$b$e^u)1(ui@'

LANGUAGE_CODE = 'es'
USE_I18N = True
USE_L10N = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'bonshop.vercel.app',
    'localhost',
    '127.0.0.1',
    'proyecto-final.duckdns.org'
]

# Application definition

INSTALLED_APPS = [
    # Apps propias
    'jazzmin',
    'corsheaders',
    'rest_framework',
    'accounts',
    'products',
    'orders',
    'communications',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_rest_passwordreset',
    'django_extensions',
    'reportlab',
    # Apps de terceros (si las hay)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

AUTH_USER_MODEL = 'accounts.Usuario'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
FRONTEND_URL = 'https://bonshop.vercel.app/'  # URL de tu app Nuxt3
#FRONTEND_URL = 'http://localhost:3000'  # URL de tu app Nuxt3
PASSWORD_RESET_URL = f'{FRONTEND_URL}/reset-password'


REST_FRAMEWORK = {
    # Paginación por defecto con 6 ítems por página
    #'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    #'PAGE_SIZE': 9,
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=10),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    # Para que podamos consultar el jti del token
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Dominio(s) autorizados para peticiones de refresh
ALLOWED_REFRESH_ORIGINS = [
    "https://bonshop.vercel.app",  # Frontend en desarrollo
    "http://localhost:3000",
    "https://proyecto-final.duckdns.org",
    "http://proyecto-final.duckdns.org",
]

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
]

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'


# Stripe
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '(Secret Key)')


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# settings.py
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#DEFAULT_FROM_EMAIL = 'tuemail@tudominio.com'

# Servidor SMTP de Gmail
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Credenciales de tu cuenta de Gmail
EMAIL_HOST_USER = 'luisrodher98@gmail.com'
EMAIL_HOST_PASSWORD = 'tnukzgdrmnsvllpz'


DJANGO_REST_PASSWORDRESET_TOKEN_CONFIG = {
    "CLASS": "django_rest_passwordreset.tokens.RandomStringTokenGenerator",
    "OPTIONS": {
        "min_length": 20,
        "max_length": 20
    }
}

# Tiempo de expiración (ejemplo: 2 horas)
DJANGO_REST_PASSWORDRESET_TOKEN_EXPIRY_HOURS = 2

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True



AUTH_USER_MODEL = 'accounts.Usuario'

# Configuración CORS
CORS_ALLOW_CREDENTIALS = True 
CORS_ALLOWED_ORIGINS = [
    "https://bonshop.vercel.app",  # Frontend en desarrollo
    "http://localhost:3000",
    "http://localhost:8000",
    "https://proyecto-final.duckdns.org",
    "http://proyecto-final.duckdns.org",
]

CSRF_TRUSTED_ORIGINS = [
    "https://bonshop.vercel.app",
    "http://localhost:3000",
    "https://proyecto-final.duckdns.org",
    "http://proyecto-final.duckdns.org",
    "http://localhost:8000",
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    'content-disposition',
    'content-type',
    'authorization',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]

ROOT_URLCONF = 'proyecto_final.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'proyecto_final.wsgi.application'


# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Motor de base de datos
        'NAME': 'proyecto',               # Nombre de la base de datos
        'USER': 'postgres',          # Usuario de la base de datos
        'PASSWORD': 'Password',  # Contraseña
        'HOST': 'Host',  # Host
        'PORT': '5432',                             # Puerto (por defecto 5432)
    },
    
    'default2': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'tienda_online',
        'USER': 'postgres',
        'PASSWORD': 'usuario',
        'HOST': 'localhost',
        'PORT': '5432',
    },   
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # Ruta a tu carpeta static global
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "BonShop",
    "site_header": "Panel de Gestión BonShop",
    "site_brand": "BonShop",
    "theme": "minty",
    "custom_css": "css/bonshop_animations.css",
    "custom_js": "js/bonshop_interactions.js",
    "related_modal_active": True,
    "changeform_format": "horizontal_tabs",
    "welcome_sign": """
        Bienvenido al Panel de Gestión de BonShop.
    """,
    "icons": {
        "auth.user": "fas fa-user-tie",
        "products.product": "fas fa-box-open",
        "orders.order": "fas fa-receipt pulse",  # Icono animado
    },
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "icon": "fas fa-home"},
        {"name": "Ver Tienda", "url": "https://bonshop.vercel.app/", "icon": "fas fa-store"},
        {"name": "Soporte", "url": "https://t.me/bonshop_soporte", "icon": "fas fa-headset"},
    ],
      #"show_ui_builder": False, Solo para desarrollo
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_flat_style": True,
    "brand_colour": "navbar-teal",
    "accent": "accent-info",
    "navbar": "navbar-dark",
    "sidebar": "sidebar-dark-teal",
    "dark_mode_theme": "darkly",
}
