# Generated by Django 5.2 on 2025-04-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
