# Generated by Django 5.2 on 2025-04-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_pedido_estado_pedido_total_alter_pago_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='factura_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
