# Generated by Django 5.2 on 2025-04-23 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_pedido_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='direccion',
        ),
    ]
