# Generated by Django 5.2 on 2025-04-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_pedido_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='calle',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_postal',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pais',
            field=models.CharField(default='', max_length=100),
        ),
    ]
