# Generated by Django 5.2 on 2025-04-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_pedido_calle_pedido_ciudad_pedido_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='calle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
