# Generated by Django 5.2 on 2025-04-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_pedido_calle_alter_pedido_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='estado_envio',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado')], default='pendiente', max_length=20),
        ),
    ]
