# Generated by Django 5.2 on 2025-04-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderitem_estado_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='estado_envio',
        ),
    ]
