# Generated by Django 5.2 on 2025-04-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_direccion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='datos_gestor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='solicitud_gestor',
            field=models.BooleanField(default=False),
        ),
    ]
