# Generated by Django 5.2 on 2025-04-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_solicitudgestor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='datos_gestor',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='solicitud_gestor',
        ),
    ]
