# Generated by Django 5.2 on 2025-06-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_usuario_datos_gestor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudgestor',
            name='direccion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitudgestor',
            name='telefono',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
